- name: Download and Run Watchtower container 
# https://github.com/v2tec/watchtower
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    state: started
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    log_driver: syslog
    log_opt:
      tag: watchtower