- name: Create Caddy Config Directory
  file:
    path: "{{ app_base }}/caddy/certs"
    mode: 0775
    state: directory
    recurse: yes

- name: Put Caddyfile in place
  
- name: Download and Run Caddy container
  docker_container:
    name: caddy
    image: abiosoft/caddy
    state: started
    restart_policy: always
    volumes:
      - "{{ app_base }}/caddy:/data"
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "{{ caddy_port }}:80"
      - "{{ caddy_port_ssl }}:443"
    log_driver: syslog
    log_opt:
      tag: caddy
    env:
      CADDYPATH: /etc/caddycerts

- name: Open Firewall port for Caddy
  ufw:
    rule: allow
    port: "{{ caddy_port }}"
    proto: tcp
    state: enabled