- name: Create Radarr Config Directory
  file:
    path: "{{ app_base }}/radarr"
    owner: "{{ run_user }}"
    group: "{{ run_user }}"
    mode: 0775
    state: directory
    recurse: yes

- name: Get UID of {{ run_user }}
  shell: id -u "{{ run_user }}"
  register: run_user_id 

- name: Download and Run Radarr container
  docker_container:
    name: radarr
    image: linuxserver/radarr
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ app_base }}/radarr:/config"
      - "{{ dl_mvcomplete }}:/downloads"
      - "{{ media_movies }}:/movies"
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "{{ radarr_port }}:7878"
    log_driver: syslog
    log_opt:
      tag: radarr
    env:
      PUID: "{{ run_user_id.stdout }}"
      GUID: "{{ run_user_id.stdout }}"
      TZ: "{{ timezone }}"

- name: Open Firewall port for Radarr
  ufw:
    rule: allow
    port: "{{ radarr_port }}"
    proto: tcp
    state: enabled