- name: Create Sonarr Config Directory
  file:
    path: "{{ app_base }}/sonarr"
    owner: "{{ run_user }}"
    group: "{{ run_user }}"
    mode: 0775
    state: directory
    recurse: yes

- name: Get UID of {{ run_user }}
  shell: id -u "{{ run_user }}"
  register: run_user_id

- name: Download and Run Sonarr container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ app_base }}/sonarr:/config"
      - "{{ dl_tvcomplete }}:/downloads"
      - "{{ media_tv }}:/tv"
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "{{ sonarr_port }}:8989"
    log_driver: syslog
    log_opt:
      tag: sonarr
    env:
      PUID: "{{ run_user_id.stdout }}"
      PGID: "{{ run_user_id.stdout }}"
      TZ: "{{ timezone }}"

- name: Open Firewall port for Sonarr
  ufw:
    rule: allow
    port: "{{ sonarr_port }}"
    proto: tcp
    state: enabled
