  - name: Make sure Ansible PPA is in place
    apt_repository:
      repo: 'ppa:ansible/ansible'
      state: present

  - name: Upgrade apt to the latest packages
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 3600

  - name: Run apt autoremove (remove un-needed files)
    apt:
      autoremove: yes

  - name: Creating {{ run_user }} group
    group:
      name: "{{ run_user }}"
      state: present

  - name: Creating {{ run_user }} user to run Docker containers as.
    user:
      name: "{{ run_user }}"
      shell: /bin/bash
      state: present
      group: "{{ run_user }}"
      append: yes

  - name: Create base folder structure and ownership to "{{ run_user }}"
    file:
      path: "{{ item }}"
      owner: "{{ run_user }}"
      group: "{{ run_user }}"
      mode: 0775
      state: directory
      recurse: yes
    with_items:
      - "{{ app_base }}"
      - "{{ dl_base }}"
      - "{{ media_base }}"
      - "{{ media_tv }}"
      - "{{ media_movies }}"
      - "{{ dl_incomplete }}"
      - "{{ dl_mvcomplete }}"
      - "{{ dl_tvcomplete }}"

  - name: Install Needed Programs and Dependencies
    apt:
      name: "{{ item }}"
      state: installed
    with_items:
    - linux-image-extra-virtual
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - curl
    - wget
    - git
    - python-pip
    - ansible

  - name: Upgrade pip
    pip:
      name: pip
      extra_args: --upgrade

  - name: Install PIP Modules
    pip:
      name: "{{ item }}"
    with_items:
    - setuptools
    - passlib
