- name: Create Ombi Config Directory
  file:
    path: "{{ app_base }}/ombi"
    owner: "{{ run_user }}"
    group: "{{ run_user }}"
    mode: 0775
    state: directory
    recurse: yes

- name: Get UID of {{ run_user }}
  shell: id -u "{{ run_user }}"
  register: run_user_id

- name: Download and Run Ombi container
  docker_container:
    name: ombi
    image: linuxserver/ombi
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ app_base }}/ombi:/config"
      - /etc/localtime:/etc/localtime:ro
    log_driver: syslog
    ports:
      - "{{ ombi_port }}:3579"
    log_opt:
      tag: ombi
    env:
      VERSION: latest
      PUID: "{{ run_user_id.stdout }}"
      GUID: "{{ run_user_id.stdout }}"
      TZ: "{{ timezone }}"

- name: Open Firewall port for Ombi
  ufw:
    rule: allow
    port: "{{ ombi_port }}"
    proto: tcp
    state: enabled